# Japanese translation for linuxmint
# Copyright (c) 2020 Rosetta Contributors and Canonical Ltd 2020
# This file is distributed under the same license as the linuxmint package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: linuxmint\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2024-06-12 13:59+0100\n"
"PO-Revision-Date: 2024-07-03 18:54+0000\n"
"Last-Translator: kmyyfz8q <Unknown>\n"
"Language-Team: Japanese <ja@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Launchpad-Export-Date: 2025-01-06 12:01+0000\n"
"X-Generator: Launchpad (build 6394e03793719e8d73f5a60b5439440e693c92f1)\n"
"Language: ja\n"

#: resources/group-code.ui:16 src/prefs.py:345
msgid "Group Code"
msgstr "グループコード"

#: resources/group-code.ui:39
msgid "You cannot communicate with computers that do not use the same code."
msgstr "同じコードを使用していないコンピューターとは通信できません。"

#: resources/group-code.ui:49 resources/main-window.ui:51
msgid "Set code"
msgstr "コードを設定"

#: resources/group-code.ui:93
msgid "Secure mode:"
msgstr "安全モード:"

#: resources/group-code.ui:106 src/prefs.py:683
msgid "OFF"
msgstr "無効"

#: resources/group-code.ui:148 resources/main-window.ui:129
#: resources/main-window.ui:1202
msgid "More information"
msgstr "詳しい情報"

#: resources/main-window.ui:80
msgid "Secure Mode disabled"
msgstr "安全モードが無効です"

#: resources/main-window.ui:170
msgid "Download folder not secure"
msgstr "ダウンロードフォルダーが安全ではありません"

#: resources/main-window.ui:335
msgid "No matching results"
msgstr "一致する結果はありません"

#: resources/main-window.ui:491
msgid "Make this remote machine a favorite in the main view"
msgstr "このリモートマシンをメインビューのお気に入りに表示します"

#: resources/main-window.ui:565
msgid "Clear inactive and completed operations"
msgstr "非アクティブな操作と、完了した操作を消去します"

#: resources/main-window.ui:584
msgid "Send files"
msgstr "ファイルを送信"

#: resources/main-window.ui:610 src/prefs.py:311
msgid "File Transfers"
msgstr "ファイル転送"

#: resources/main-window.ui:631 src/warpinator.py:1054
msgid "Online"
msgstr "オンライン"

#: resources/main-window.ui:751
msgid "No other computers found..."
msgstr "他のコンピューターが見つかりません..."

#: resources/main-window.ui:816
msgid "Make sure your network connection is active."
msgstr "ネットワークへの接続が正常であるかを確認してください。"

#: resources/main-window.ui:831
msgid ""
"Check your firewall rules.  The port numbers can be changed.  See "
"preferences for more details."
msgstr "ファイアウォールのルールを確認してください。ポート番号は変更できます。詳細については設定を参照してください。"

#. Do not translate 'Warpinator'
#: resources/main-window.ui:847
msgid ""
"Is Warpinator running on any other computers on this network?  If so, make "
"sure they are all using the same group code in preferences."
msgstr ""
"Warpinator "
"がネットワーク上の他のコンピューターでも実行されていますか？もしそうなら、グループコードの設定値がすべてのマシンで同じになっていることを確認してください。"

#: resources/main-window.ui:865
msgid "Possible solutions:"
msgstr "考えられる解決策:"

#. Do not translate 'Warpinator'
#: resources/main-window.ui:900
msgid "Warpinator is also available on:"
msgstr "Warpinator は次においても利用できます:"

#: resources/main-window.ui:915
msgid "Android"
msgstr "Android"

#: resources/main-window.ui:931 resources/main-window.ui:946
msgid "Windows"
msgstr "Windows"

#: resources/main-window.ui:1020
msgid "Initializing, please wait..."
msgstr "初期化しています、お待ちください..."

#: resources/main-window.ui:1078
msgid "Something went wrong"
msgstr "問題が発生しました"

#: resources/main-window.ui:1153
msgid "Invalid save location"
msgstr "保存先の場所が無効です"

#: resources/main-window.ui:1190
msgid ""
"This folder is either inaccessible or forbidden to save files to.  Please "
"select a new location in Preferences and ensure that it is accessible."
msgstr ""
"このフォルダーにはアクセスできないか、ファイルを保存する許可がありません。  設定から新しい場所を選択し、アクセスできるかどうかを確認してください。"

#: resources/main-window.ui:1262
msgid "Searching for other computers"
msgstr "他のコンピューターを検索しています"

#: resources/main-window.ui:1321
msgid "Shutting down..."
msgstr "シャットダウンしています..."

#: resources/main-window.ui:1393
msgid "Restart required"
msgstr "再起動が必要です"

#: resources/main-window.ui:1410
msgid "Warpinator needs to restart before the new save directory can be used"
msgstr "新しい保存先のフォルダーを使用する前に Warpinator を再起動する必要があります"

#: resources/main-window.ui:1420
msgid "Restart"
msgstr "再起動"

#: resources/main-window.ui:1490
msgid "Disk Full"
msgstr "ディスクがいっぱいです"

#: resources/main-window.ui:1527
msgid ""
"There is insufficient space available in the save location. You need to "
"delete some files, decrease the minimum free space in preferences or choose "
"a new location."
msgstr ""
"保存先となる場所に十分な空き容量がありません。何かファイルを削除するか、設定で確保している最小の容量を減らすか、新しい保存先を指定してください。"

#: resources/main-window.ui:1544
msgid "Empty trash"
msgstr "ゴミ箱を空にする"

#: resources/main-window.ui:1558 src/warpinator.py:563 src/warpinator.py:1643
msgid "Open save folder"
msgstr "保存先のフォルダーを開く"

#: resources/main-window.ui:1571
msgid "Examine disk usage"
msgstr "ディスクの使用率を調査"

#: resources/main-window.ui:1624 src/util.py:774
#: data/org.x.Warpinator.desktop.in.in:5
msgid "Send and Receive Files across the Network"
msgstr "ネットワーク経由でファイルを送受信します"

#. manual-connect dialog: first main section header (bold, big)
#: resources/manual-connect.ui:22
msgid "On this computer:"
msgstr "このコンピューターで:"

#. The user enters an IP address and port in an entry below this
#: resources/manual-connect.ui:38
msgid "Enter the address of the device you want to connect to"
msgstr "接続したいデバイスのアドレスを入力します"

#: resources/manual-connect.ui:70
msgid "Connect"
msgstr "接続"

#. manual-connect dialog: second main section header (bold, big)
#: resources/manual-connect.ui:134
msgid "Alternatively, on the other device:"
msgstr "あるいは、他のデバイスで:"

#. A qr code is displayed below this
#: resources/manual-connect.ui:150
msgid "Scan this QR code"
msgstr "この QR コードをスキャンします"

#. The user's ip address and port are displayed here
#: resources/manual-connect.ui:198
msgid "Or connect to the address below"
msgstr "または、下のアドレスに接続します"

#: resources/op-item.ui:140
msgid "Awaiting approval"
msgstr "承認待ち"

#: resources/op-item.ui:156
msgid "Not enough disk space!"
msgstr "ディスク容量が足りません！"

#: resources/op-item.ui:219
msgid "Calculating"
msgstr "計算しています"

#: resources/op-item.ui:259
msgid "Accept this request"
msgstr "この要求を承認します"

#: resources/op-item.ui:274
msgid "Refuse this request"
msgstr "この要求を拒否します"

#: resources/op-item.ui:289
msgid "Cancel this request"
msgstr "この要求をキャンセルします"

#: resources/op-item.ui:304
msgid "Restart this operation"
msgstr "この操作を再試行します"

#: resources/op-item.ui:319
msgid "Pause this operation"
msgstr "この操作を一時停止します"

#: resources/op-item.ui:334
msgid "Resume this operation"
msgstr "この操作を再開します"

#: resources/op-item.ui:349
msgid "Cancel this operation"
msgstr "この操作をキャンセルします"

#: resources/op-item.ui:364
msgid "Remove this operation from the list"
msgstr "この操作を一覧から削除します"

#: resources/op-item.ui:379
msgid "Open the containing folder"
msgstr "含まれているフォルダーを開きます"

#: resources/prefs-window.ui:9
msgid "Note on port numbers:"
msgstr "ポート番号に関する注意:"

#. Do not translate 'Warpinator'
#: resources/prefs-window.ui:24
msgctxt "preferences window title"
msgid "Warpinator Preferences"
msgstr "Warpinator の設定"

#: src/notifications.py:24
msgid "New incoming files"
msgstr "新しい着信ファイル"

#: src/notifications.py:30
#, python-format
msgid ""
"%(sender_name)s would like to send you %(file_count)d file (%(file_name)s)."
msgstr ""
"%(sender_name)s が %(file_count)d 個のファイル (%(file_name)s) を送信しようとしています。"

#: src/notifications.py:31
#, python-format
msgid "%(sender_name)s would like to send you %(file_count)d files"
msgstr "%(sender_name)s が %(file_count)d 個のファイルを送信しようとしています"

#: src/notifications.py:41
msgid "Accept"
msgstr "承認"

#: src/notifications.py:42
msgid "Decline"
msgstr "拒否"

#: src/notifications.py:56
#, python-format
msgid "%(sender_name)s is sending you %(file_count)d file (%(file_name)s)."
msgstr "%(sender_name)s が %(file_count)d 個のファイル (%(file_name)s) を送信しています。"

#: src/notifications.py:57
#, python-format
msgid "%(sender_name)s is sending you %(file_count)d files"
msgstr "%(sender_name)s が %(file_count)d 個のファイルを送信しています"

#: src/notifications.py:93
msgid "Transfer complete"
msgstr "転送完了"

#: src/notifications.py:96
#, python-format
msgid "The transfer to %s has finished, but with errors"
msgstr "%s への転送は完了しましたが、エラーがありました"

#: src/notifications.py:98
#, python-format
msgid "The transfer to %s has finished successfully"
msgstr "%s への転送に成功しました"

#: src/notifications.py:101
#, python-format
msgid "The transfer from %s has finished, but with errors"
msgstr "%s からの転送は完了しましたが、エラーがありました"

#: src/notifications.py:103
#, python-format
msgid "The transfer from %s has finished successfully"
msgstr "%s からの転送に成功しました"

#: src/notifications.py:137 src/warpinator.py:173 src/warpinator.py:176
msgid "Transfer failed"
msgstr "転送失敗"

#: src/notifications.py:140
#, python-format
msgid "Something went wrong with the transfer to %s"
msgstr "%s への転送に問題が発生しました"

#: src/notifications.py:142
#, python-format
msgid "Something went wrong with the transfer from %s"
msgstr "%s からの転送に問題が発生しました"

#: src/notifications.py:171 src/warpinator.py:167
msgid "Transfer cancelled"
msgstr "転送がキャンセルされました"

#: src/notifications.py:174
#, python-format
msgid "Your transfer to %s was cancelled"
msgstr "%s への転送がキャンセルされました"

#: src/notifications.py:176
#, python-format
msgid "An incoming transfer from %s was cancelled"
msgstr "%s からの転送がキャンセルされました"

#: src/notifications.py:204
msgid "Sending files"
msgstr "ファイルを送信しています"

#: src/notifications.py:207
#, python-format
msgid "Sending %d files to %s"
msgstr "%d 個のファイルを %s に送信しています"

#: src/notifications.py:209
#, python-format
msgid "Sending '%s' to %s"
msgstr "'%s' を %s に送信しています"

#: src/ops.py:53
#, python-format
msgid "%(time_left)s (%(bytes_per_sec)s/s)"
msgstr "%(time_left)s (%(bytes_per_sec)s/秒)"

#. Translators: Don't need to translate singular, we show the filename if there's only one
#: src/ops.py:154
#, python-format
msgid "%d file-do-not-translate"
msgid_plural "%d files"
msgstr[0] "%d 個のファイル"

#. Translators: Don't need to translate singular, we show the filename if there's only one
#: src/ops.py:261
#, python-format
msgid "%d file"
msgid_plural "%d files"
msgstr[0] "%d 個のファイル"

#: src/prefs.py:276
msgid "Warpinator Preferences"
msgstr "Warpinator の設定"

#: src/prefs.py:293
msgid "General"
msgstr "一般"

#: src/prefs.py:295
msgid "Desktop"
msgstr "デスクトップ"

#: src/prefs.py:297
msgid "Show an icon in the notification area"
msgstr "通知領域にアイコンを表示"

#: src/prefs.py:301
msgid "Start with main window open"
msgstr "開始時にメインウィンドウを開く"

#: src/prefs.py:306
msgid "Start automatically"
msgstr "自動的に開始"

#: src/prefs.py:313
msgid "Use compression when possible."
msgstr "可能であれば圧縮。"

#: src/prefs.py:315
msgid ""
"Warning: This may have a negative impact on performance on some faster "
"networks."
msgstr "注: これは､高速ネットワークでパフォーマンスに悪影響をもたらすかもしれません。"

#: src/prefs.py:318
msgid "Location for received files"
msgstr "受信したファイルの場所"

#: src/prefs.py:323
msgid "Reserved free space"
msgstr "確保しておく空き容量"

#: src/prefs.py:328
msgid "Require approval before accepting files"
msgstr "ファイルを受け入れる前に承認を要求"

#: src/prefs.py:333
msgid "Require approval when files would be overwritten"
msgstr "ファイルが上書きされるときに承認を要求"

#: src/prefs.py:338
msgid ""
"Display a notification when someone sends (or tries to send) you files"
msgstr "このマシンにファイルが送信されたり、送信されようとしたら通知を表示"

#: src/prefs.py:343
msgid "Connection"
msgstr "接続"

#: src/prefs.py:353
msgid "Network"
msgstr "ネットワーク"

#: src/prefs.py:356
msgid "Automatic"
msgstr "自動"

#. translation: combobox item shown when a previosuly set interface can no longer be found - 'wlan0 - not found'
#: src/prefs.py:435
#, python-format
msgid "%s - not found"
msgstr "%s - 見つかりません"

#: src/prefs.py:437
msgid "Network interface to use"
msgstr "使用するネットワークインタフェース"

#: src/prefs.py:445
msgid "Incoming port for transfers"
msgstr "転送用の着信ポート"

#: src/prefs.py:452
msgid "Incoming port for registration"
msgstr "登録用の着信ポート"

#: src/prefs.py:467
msgid "Apply network changes"
msgstr "ネットワークの変更を適用"

#: src/prefs.py:476
msgid "Update firewall rules"
msgstr "ファイアウォールのルールを更新"

#: src/prefs.py:488
msgid ""
"Any port numbers will work for the application, but using the same ports for "
"all computers can make it simpler to add firewall exceptions if necessary."
msgstr ""
"どのポート番号でもアプリケーションは機能しますが、すべてのコンピューターで同じポート番号を使用すると、ファイアウォールの例外が設定しやすくなります。"

#: src/prefs.py:564
msgid "Only available in secure mode."
msgstr "安全モードでのみ利用できます。"

#: src/prefs.py:641
msgid "A group code is required."
msgstr "グループコードが必要です。"

#: src/prefs.py:646
msgid "The group code is too short."
msgstr "グループコードが短すぎます。"

#: src/prefs.py:680
msgid "ON"
msgstr "有効"

#: src/prefs.py:681
msgid "All options are unlocked."
msgstr "すべてのオプションが開放されました。"

#: src/prefs.py:684
msgid ""
"You must set a custom group code to run in secure mode. Some options are "
"currently disabled."
msgstr "安全モードで実行するには、任意のグループコードを設定してください。いくつかのオプションは無効になっています。"

#: src/remote.py:643 src/remote.py:647
msgid "Connection has been lost"
msgstr "接続が切断されました"

#: src/server.py:648
msgid "An error occurred on the remote machine"
msgstr "リモートマシンでエラーが発生しました"

#: src/util.py:269
msgid "Cancel"
msgstr "キャンセル"

#: src/util.py:270
msgid "Add"
msgstr "追加"

#: src/util.py:292
msgid "Select file(s) to send"
msgstr "送信するファイルを選択"

#: src/util.py:663
msgid "A few seconds remaining"
msgstr "残り数秒"

#: src/util.py:666
#, python-format
msgid "%d seconds remaining"
msgstr "残り %d 秒"

#: src/util.py:670 src/util.py:678
#, python-format
msgid "%d minute"
msgid_plural "%d minutes"
msgstr[0] "%d 分"

#: src/util.py:677
#, python-format
msgid "%d hour"
msgid_plural "%d hours"
msgstr[0] "%d 時間"

#: src/util.py:682
#, python-format
msgid "approximately %d hour"
msgid_plural "approximately %d hours"
msgstr[0] "およそ %d 時間"

#: src/util.py:770 src/warpinator.py:585
msgid "About"
msgstr "このアプリケーションについて"

#: src/warpinator.py:146
msgid "Paused"
msgstr "一時停止"

#: src/warpinator.py:149
msgid "Waiting for approval"
msgstr "承認待ち"

#: src/warpinator.py:151
msgid "Waiting for your approval"
msgstr "あなたの承認待ち"

#: src/warpinator.py:154
msgid "Not enough disk space"
msgstr "ディスクの容量が足りません"

#: src/warpinator.py:157
msgid "Files may be overwritten"
msgstr "ファイルが上書きされる可能性があります"

#: src/warpinator.py:160
msgid "Request cancelled"
msgstr "要求をキャンセルしました"

#: src/warpinator.py:162 src/warpinator.py:164
#, python-format
msgid "Request cancelled by %s"
msgstr "要求が %s によってキャンセルされました"

#: src/warpinator.py:169 src/warpinator.py:171
#, python-format
msgid "Transfer cancelled by %s"
msgstr "転送が %s によってキャンセルされました"

#: src/warpinator.py:178
#, python-format
msgid "File '%s' not found"
msgstr "ファイル '%s' が見つかりません"

#: src/warpinator.py:180
msgid "Some files not found"
msgstr "一部のファイルが見つかりません"

#: src/warpinator.py:182
msgid "Completed"
msgstr "完了"

#: src/warpinator.py:184
msgid "Completed, but with errors"
msgstr "完了しましたが、エラーがありました"

#: src/warpinator.py:343 src/warpinator.py:1082
msgid "Connecting"
msgstr "接続しています"

#: src/warpinator.py:345
#, python-format
msgid "Connecting to %s"
msgstr "%s に接続しています"

#: src/warpinator.py:355
#, python-format
msgid "%s is not online"
msgstr "%s はオフラインです"

#: src/warpinator.py:360
#, python-format
msgid "Cannot connect to %s"
msgstr "%s に接続できません"

#: src/warpinator.py:365
#, python-format
msgid "Waiting for %s to complete the connection."
msgstr "%s の接続が完了するのを待機しています。"

#: src/warpinator.py:394
#, python-format
msgid "%d new incoming transfer"
msgid_plural "%d new incoming transfers"
msgstr[0] "新しい %d 件の転送が受信できます"

#: src/warpinator.py:536 src/warpinator.py:1697
msgid "Favorites"
msgstr "お気に入り"

#: src/warpinator.py:541 src/warpinator.py:1702
msgid "Recents"
msgstr "最近使ったファイル"

#: src/warpinator.py:548 src/warpinator.py:1711
msgid "Browse..."
msgstr "参照..."

#: src/warpinator.py:569
msgid "Connect manually"
msgstr "手動で接続"

#: src/warpinator.py:574
msgid "Restart service"
msgstr "サービスを再起動"

#: src/warpinator.py:581 data/org.x.Warpinator.appdata.xml.in.in:57
msgid "Preferences"
msgstr "設定"

#: src/warpinator.py:589 src/warpinator.py:1646
msgid "Quit"
msgstr "終了"

#: src/warpinator.py:698
msgid "You don't appear to be connected to a network."
msgstr "ネットワークに接続されていないようです。"

#: src/warpinator.py:700
msgid "Startup was unsuccessful, please check your logs."
msgstr "開始に失敗しました。ログを確認してください。"

#: src/warpinator.py:800
#, python-format
msgid ""
"Warpinator is running with limited functionality, and will exit in %d "
"minute. To enable Secure Mode, set a unique group code."
msgstr ""
"Warpinator は機能制限付きで実行されており、あと %d 分で終了します。安全モードを有効にするには、一意なグループコードを設定してください。"

#: src/warpinator.py:802
#, python-format
msgid ""
"Warpinator is running with limited functionality, and will exit in %d "
"minutes. To enable Secure Mode, set a unique group code."
msgstr ""
"Warpinator は機能制限付きで実行されており、あと %d 分で終了します。安全モードを有効にするには、一意なグループコードを設定してください。"

#: src/warpinator.py:857
#, python-format
msgid "Not enough disk space remaining to receive files (%s is reserved)."
msgstr "ファイルを受信するために十分な空き容量がありません (%s を確保しています)。"

#: src/warpinator.py:938
#, python-format
msgid "Waiting for %d operation to complete"
msgstr "%d 件の操作の完了を待機しています"

#: src/warpinator.py:939
#, python-format
msgid "Waiting for %d operations to complete"
msgstr "%d 件の操作の完了を待機しています"

#: src/warpinator.py:1061
msgid "Offline"
msgstr "オフライン"

#: src/warpinator.py:1068
msgid "Unable to connect"
msgstr "接続できません"

#: src/warpinator.py:1075
msgid "Waiting for two-way connection"
msgstr "双方向接続を待機しています"

#: src/warpinator.py:1176
msgid "Manual connection"
msgstr "手動での接続"

#: src/warpinator.py:1243
msgid "Connecting..."
msgstr "接続しています..."

#: src/warpinator.py:1680
msgid "Send to all"
msgstr "すべてに送信"

#: data/warpinator-send.nemo_action.in:4
msgid "Send with Warpinator"
msgstr "Warpinator で送信"

#: data/warpinator-send.nemo_action.in:5
msgid "Send a file to someone using Warpinator"
msgstr "Warpinator の使用者にファイルを送信"

#: data/org.x.warpinator.policy.in.in:12
msgid "Open a firewall port for Warpinator"
msgstr "Warpinator 用のファイアウォールのポートを開く"

#: data/org.x.warpinator.policy.in.in:13
msgid "To modify firewall settings, you need to authenticate."
msgstr "ファイアウォールの設定を変更するには、認証が必要です。"

#. DO NOT TRANSLATE Warpinator
#: data/org.x.Warpinator.appdata.xml.in.in:10
msgid "Warpinator"
msgstr "Warpinator"

#: data/org.x.Warpinator.appdata.xml.in.in:11
msgid "Share files on your network"
msgstr "ネットワーク上でファイルを共有します"

#: data/org.x.Warpinator.appdata.xml.in.in:13
msgid ""
"Warpinator allows you to easily connect multiple computers on a local area "
"network and exchange files quickly and securely."
msgstr "Warpinator でローカルエリアネットワーク上の複数のコンピューターを簡単に接続し、ファイルを素早く安全に交換できます。"

#: data/org.x.Warpinator.appdata.xml.in.in:14
msgid "Features:"
msgstr "特徴:"

#: data/org.x.Warpinator.appdata.xml.in.in:16
msgid "An easy-to-use graphical interface."
msgstr "使いやすいグラフィカルインタフェースを備えています。"

#: data/org.x.Warpinator.appdata.xml.in.in:17
msgid "Automatic discovery of devices on your network."
msgstr "ネットワーク上にあるデバイスを自動的に検出します。"

#: data/org.x.Warpinator.appdata.xml.in.in:18
msgid "Fully secure and encrypted connections between devices."
msgstr "デバイス間の接続は暗号化されるため、安全に通信できます。"

#: data/org.x.Warpinator.appdata.xml.in.in:19
msgid "Multiple simultaneous transfers."
msgstr "複数のファイルを同時に転送できます。"

#: data/org.x.Warpinator.appdata.xml.in.in:20
msgid "Optional data compression."
msgstr "必要に応じてデータは圧縮させられます。"

#: data/org.x.Warpinator.appdata.xml.in.in:21
msgid ""
"Grouping of devices using a shared key, with multiple groups possible on the "
"same network."
msgstr "共有鍵でデバイスをグループごとに別けると、同一のネットワーク上で複数のグループを混在させられます。"

#: data/org.x.Warpinator.appdata.xml.in.in:22
msgid "Manual connections for restricted network environments."
msgstr "制限付きのネットワーク環境下でも、手動での接続が行えます。"

#: data/org.x.Warpinator.appdata.xml.in.in:45
msgid "The main view showing connected devices and their status"
msgstr "接続しているデバイスと、その状態を確認できるメインビュー"

#: data/org.x.Warpinator.appdata.xml.in.in:49
msgid ""
"Individual connection page showing individual incoming or outgoing transfers"
msgstr "送受信しているファイルそれぞれを確認できる、個々の接続ページ"

#: data/org.x.Warpinator.appdata.xml.in.in:53
msgid "Manual connection dialog"
msgstr "手動での接続ダイアログ"
